FROM 192.168.13.252:5050/node:22-alpine as builder
ENV NODE_ENV development
WORKDIR /app
COPY . .
COPY build.sh ./build.sh
RUN chmod +x ./build.sh
RUN ./build.sh

FROM 192.168.13.252:5050/nginx:1.27.1-alpine as production
ENV NODE_ENV production
#RUN apk add --no-cache nginx-mod-http-brotli
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
