server {
    listen 80;
    charset utf-8;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    large_client_header_buffers 32 64k;
    
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
    gzip_comp_level 9; ##############6;
    gzip_proxied any;

#     brotli on;
#     brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
#     brotli_static on;
#     brotli_comp_level 6;

    location / {
        alias /usr/share/nginx/html/;
        include /etc/nginx/mime.types;
        try_files $uri $uri/ /index.html;
    }

    location /mikhak_backend/ {
        proxy_pass http://192.168.13.72:32333/;
        # http://svc-dezhban-api.dezhban-api.svc.cluster.local:8000/
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;    ###########
        proxy_set_header X-Forwarded-Proto $scheme; ###########
        proxy_redirect off;

        # Increase timeouts
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 600;

        ######################################
        proxy_buffer_size          1024k;
        proxy_buffers              8 2048k;
        proxy_busy_buffers_size    2048k;
        client_body_buffer_size    10M;

#            large_client_header_buffers 4 128k;

        # Allow large POST bodies
        client_max_body_size 100M;

        # Forward HTTP methods & body correctly
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    
        ########################################

        rewrite ^/mikhak_backend(/.*)$ $1 break;
    }

    location /manifest.webmanifest {
      add_header Cache-Control "no-cache";
    }

    location /sw.js {
       root /usr/share/nginx/html;
       add_header Cache-Control "no-cache";
    }

    # location /admin/mikhak/ {
    #     rewrite ^/admin(/mikhak/.*)$ $1 break;
    #     proxy_pass http://192.168.13.49:9000;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header Host $host;
    #     #proxy_redirect off;
    # }

    location /mikhak/ {
        proxy_pass http://192.168.13.49:9000/mikhak/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }

    location /mikhak_backend/api/base/stream/ {
        proxy_pass http://svc-dezhban-api.dezhban-api.svc.cluster.local:8000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}
