apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $MICRO_SERVICE
  name: $MICRO_SERVICE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $MICRO_SERVICE
  template:
    metadata:
      labels:
        app: $MICRO_SERVICE
    spec:
      imagePullSecrets:
      - name: $SECRET_NAME
      containers:
      - image: $IMAGE_NAME:$IMAGE_TAG
        name: $MICRO_SERVICE
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "1000Mi"
            cpu: "800m"
        ports:
        - containerPort: $CONTAINER_PORT
      restartPolicy: Always
